import { useEffect, useState, useRef, useMemo, CSSProperties } from "react";
import { motion, useMotionValueEvent, useTransform } from "motion/react";
import { useScrollModule } from "../use-scroll-module";

import { getStoryAssetUrl } from "../../../../../../../libs/get-story-asset-urls";
import {
  getImageSequenceFrameIndex,
  getImageSequenceManifestSrc,
  getImageSequenceFrameSrc,
  ImageSequenceManifest,
  ImageSequenceSource,
} from "../../../../../../../libs/image-sequence";
import { useStory } from "../../../../../../../providers/story/use-story";

import cx from "classnames";

import styles from "./scroll-image-sequence.module.css";

interface Props {
  className: string;
  sequence: ImageSequenceSource;
}

interface ScrollImageSequenceConfig {
  imageSequence: {
    progressRange: [number, number];
    input?: Array<number>;
    output?: Array<number>;
  };
}

export default function ScrollImageSequence({ className, sequence }: Props) {
  const { scrollYProgress, config } =
    useScrollModule<ScrollImageSequenceConfig>();

  const { story } = useStory();
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const imagesRef = useRef<Array<HTMLImageElement | undefined>>([]);
  const lastRenderedFrameRef = useRef(-1);
  const pendingFrameRef = useRef(0);

  const [manifest, setManifest] = useState<ImageSequenceManifest | null>(null);
  const progressRange = useMemo(
    () => config.imageSequence.progressRange ?? [0, 1],
    [config.imageSequence.progressRange],
  );

  const frameBasePath = getStoryAssetUrl(story?.id ?? "", sequence.path);
  const manifestSrc = getImageSequenceManifestSrc(frameBasePath);

  const drawFrame = (frameIndex: number) => {
    const image = imagesRef.current[frameIndex];
    const canvas = canvasRef.current;
    const context = canvas?.getContext("2d");

    if (
      !image ||
      !canvas ||
      !context ||
      !image.complete ||
      !image.naturalWidth
    ) {
      return false;
    }

    if (
      canvas.width !== image.naturalWidth ||
      canvas.height !== image.naturalHeight
    ) {
      canvas.width = image.naturalWidth;
      canvas.height = image.naturalHeight;
    }

    context.clearRect(0, 0, canvas.width, canvas.height);
    context.drawImage(image, 0, 0, canvas.width, canvas.height);
    lastRenderedFrameRef.current = frameIndex;

    return true;
  };

  useEffect(() => {
    let isCancelled = false;

    lastRenderedFrameRef.current = -1;

    // The manifest is the source of truth for sequence metadata generated by the frame extraction script.
    fetch(manifestSrc)
      .then((response) => {
        if (!response.ok) {
          throw new Error(
            `Failed to load image sequence manifest: ${manifestSrc}`,
          );
        }

        return response.json() as Promise<ImageSequenceManifest>;
      })
      .then((nextManifest) => {
        if (isCancelled) {
          return;
        }

        setManifest(nextManifest);
      })
      .catch((error) => {
        console.error(error.message);
      });

    return () => {
      isCancelled = true;
    };
  }, [manifestSrc]);

  useEffect(() => {
    const frameCount = manifest?.frameCount;

    if (!frameCount || frameCount <= 0) {
      imagesRef.current = [];
      return;
    }

    imagesRef.current = new Array(frameCount);
    lastRenderedFrameRef.current = -1;
    pendingFrameRef.current = getImageSequenceFrameIndex(
      scrollYProgress.get(),
      progressRange,
      frameCount,
    );

    let isCancelled = false;

    // Preload the full sequence so scroll progress can map directly to already-created image objects.
    for (let index = 0; index < frameCount; index += 1) {
      const image = new Image();

      image.decoding = "async";
      image.src = getImageSequenceFrameSrc(frameBasePath, index);
      image.onload = () => {
        if (isCancelled) {
          return;
        }

        // If scroll moved ahead before this frame loaded, prefer the latest requested frame over stale ones.
        if (index === pendingFrameRef.current) {
          drawFrame(index);
          return;
        }

        if (index === 0 && lastRenderedFrameRef.current === -1) {
          drawFrame(index);
        }
      };
      image.onerror = () => {
        console.warn(`Failed to load image sequence frame: ${image.src}`);
      };

      imagesRef.current[index] = image;
    }

    return () => {
      isCancelled = true;
      imagesRef.current = [];
    };
  }, [frameBasePath, manifest, progressRange, scrollYProgress]);

  useMotionValueEvent(scrollYProgress, "change", (latest) => {
    const frameCount = manifest?.frameCount;

    if (!frameCount || frameCount <= 0) {
      return;
    }

    // Scroll progress drives frame selection directly instead of relying on media playback state.
    const frameIndex = getImageSequenceFrameIndex(
      latest,
      progressRange,
      frameCount,
    );

    pendingFrameRef.current = frameIndex;

    if (frameIndex === lastRenderedFrameRef.current) {
      return;
    }

    drawFrame(frameIndex);
  });

  const imageSequenceInputRange = config.imageSequence.input ?? [];
  const imageSequenceOutputRange = config.imageSequence.output ?? [];

  const opacity = useTransform(
    scrollYProgress,
    imageSequenceInputRange,
    imageSequenceOutputRange,
  );

  return (
    <motion.div
      className={cx(styles.sequenceContainer, className)}
      style={
        {
          "--sequence-opacity": opacity,
        } as CSSProperties
      }
    >
      <canvas
        ref={canvasRef}
        className={styles.scrollImageSequence}
        aria-hidden="true"
      />
    </motion.div>
  );
}
