import {
  useEffect,
  useState,
  useRef,
  useMemo,
  CSSProperties,
  useCallback,
} from "react";
import { motion, useMotionValueEvent, useTransform } from "motion/react";
import { useScrollModule } from "../use-scroll-module";

import { useScreenInfo } from "../../../../../../../hooks/use-screen-info";
import { getStoryAssetUrl } from "../../../../../../../libs/get-story-asset-urls";
import {
  getImageSequenceFrameIndex,
  getImageSequenceManifestSrc,
  getImageSequenceFrameSrc,
  ImageSequenceManifest,
  ImageSequenceSource,
} from "../../../../../../../libs/image-sequence";
import { useStory } from "../../../../../../../providers/story/use-story";

import cx from "classnames";

import styles from "./scroll-image-sequence.module.css";

interface Props {
  className: string;
  sequence: ImageSequenceSource;
}

interface ScrollImageSequenceConfig {
  imageSequence: {
    progressRange: [number, number];
    input?: Array<number>;
    output?: Array<number>;
  };
}

/**
 * How to add an image-sequence scroll module:
 *
 * 1. Make sure `ffmpeg` is installed.
 * 2. Run `scripts/extract-video-frames.js` with an input video and output directory.
 *    The script generates the frame files and `image-sequence.json` manifest.
 * 3. Add this to the story module content:
 *    ```json
 *    "imageSequence": {
 *      "path": "assets/your-path-here"
 *    }
 *    ```
 * 4. Add `ScrollImageSequence` component to the module root and pass props.
 * 5. Optional: set `imageSequence.progressRange` in the animation config to map the
 *    sequence to a subset of the module scroll progress. For example, `[0.2, 0.8]`
 *    starts the sequence at 20% progress and finishes it by 80%. Defaults to `[0, 1]`.
 * 6. Optional: for fade in / out adapt opacity values in animationConfig
 */
export default function ScrollImageSequence({ className, sequence }: Props) {
  const { scrollYProgress, config } =
    useScrollModule<ScrollImageSequenceConfig>();

  const { isMobile } = useScreenInfo();
  const { story } = useStory();
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const imagesRef = useRef<Array<HTMLImageElement | undefined>>([]);
  const lastRenderedFrameRef = useRef(-1);
  const pendingFrameRef = useRef(0);

  const [manifest, setManifest] = useState<ImageSequenceManifest | null>(null);
  const progressRange = useMemo(
    () => config.imageSequence.progressRange ?? [0, 1],
    [config.imageSequence.progressRange],
  );

  const frameBasePath = getStoryAssetUrl(story?.id ?? "", sequence.path);
  const manifestSrc = getImageSequenceManifestSrc(frameBasePath);

  const drawImageCover = useCallback(
    (
      context: CanvasRenderingContext2D,
      image: HTMLImageElement,
      canvas: HTMLCanvasElement,
    ) => {
      // use scale here to preserve aspect ratio
      const scale = Math.max(
        canvas.width / image.naturalWidth,
        canvas.height / image.naturalHeight,
      );

      const drawWidth = image.naturalWidth * scale;
      const drawHeight = image.naturalHeight * scale;
      const offsetX = (canvas.width - drawWidth) / 2;
      const offsetY = (canvas.height - drawHeight) / 2;

      context.drawImage(image, offsetX, offsetY, drawWidth, drawHeight);
    },
    [],
  );

  const drawFrame = useCallback(
    (frameIndex: number) => {
      const image = imagesRef.current[frameIndex];
      const canvas = canvasRef.current;
      const context = canvas?.getContext("2d");

      if (
        !image ||
        !canvas ||
        !context ||
        !image.complete ||
        !image.naturalWidth
      ) {
        return false;
      }

      const nextCanvasWidth = isMobile
        ? Math.max(canvas.clientWidth, 1)
        : image.naturalWidth;
      const nextCanvasHeight = isMobile
        ? Math.max(canvas.clientHeight, 1)
        : image.naturalHeight;

      if (
        canvas.width !== nextCanvasWidth ||
        canvas.height !== nextCanvasHeight
      ) {
        canvas.width = nextCanvasWidth;
        canvas.height = nextCanvasHeight;
      }

      context.clearRect(0, 0, canvas.width, canvas.height);

      if (isMobile) {
        drawImageCover(context, image, canvas);
      } else {
        context.drawImage(image, 0, 0, canvas.width, canvas.height);
      }

      lastRenderedFrameRef.current = frameIndex;

      return true;
    },
    [drawImageCover, isMobile],
  );

  useEffect(() => {
    let isCancelled = false;

    lastRenderedFrameRef.current = -1;

    // The manifest is the source of truth for sequence metadata generated by the frame extraction script.
    fetch(manifestSrc)
      .then((response) => {
        if (!response.ok) {
          throw new Error(
            `Failed to load image sequence manifest: ${manifestSrc}`,
          );
        }

        return response.json() as Promise<ImageSequenceManifest>;
      })
      .then((nextManifest) => {
        if (isCancelled) {
          return;
        }

        setManifest(nextManifest);
      })
      .catch((error) => {
        console.error(error.message);
      });

    return () => {
      isCancelled = true;
    };
  }, [manifestSrc]);

  useEffect(() => {
    const frameCount = manifest?.frameCount;

    if (!frameCount || frameCount <= 0) {
      imagesRef.current = [];
      return;
    }

    imagesRef.current = new Array(frameCount);
    lastRenderedFrameRef.current = -1;
    pendingFrameRef.current = getImageSequenceFrameIndex(
      scrollYProgress.get(),
      progressRange,
      frameCount,
    );

    let isCancelled = false;

    // Preload the full sequence so scroll progress can map directly to already-created image objects.
    for (let index = 0; index < frameCount; index += 1) {
      const image = new Image();

      image.decoding = "async";
      image.src = getImageSequenceFrameSrc(frameBasePath, index);
      image.onload = () => {
        if (isCancelled) {
          return;
        }

        // If scroll moved ahead before this frame loaded, prefer the latest requested frame over stale ones.
        if (index === pendingFrameRef.current) {
          drawFrame(index);
          return;
        }

        if (index === 0 && lastRenderedFrameRef.current === -1) {
          drawFrame(index);
        }
      };
      image.onerror = () => {
        console.warn(`Failed to load image sequence frame: ${image.src}`);
      };

      imagesRef.current[index] = image;
    }

    return () => {
      isCancelled = true;
      imagesRef.current = [];
    };
  }, [drawFrame, frameBasePath, manifest, progressRange, scrollYProgress]);

  useMotionValueEvent(scrollYProgress, "change", (latest) => {
    const frameCount = manifest?.frameCount;

    if (!frameCount || frameCount <= 0) {
      return;
    }

    // Scroll progress drives frame selection directly instead of relying on media playback state.
    const frameIndex = getImageSequenceFrameIndex(
      latest,
      progressRange,
      frameCount,
    );

    pendingFrameRef.current = frameIndex;

    if (frameIndex === lastRenderedFrameRef.current) {
      return;
    }

    drawFrame(frameIndex);
  });

  const imageSequenceInputRange = config.imageSequence.input ?? [];
  const imageSequenceOutputRange = config.imageSequence.output ?? [];

  const opacity = useTransform(
    scrollYProgress,
    imageSequenceInputRange,
    imageSequenceOutputRange,
  );

  return (
    <motion.div
      className={cx(styles.sequenceContainer, className)}
      style={
        {
          "--sequence-opacity": opacity,
        } as CSSProperties
      }
    >
      <canvas
        ref={canvasRef}
        className={styles.scrollImageSequence}
        aria-hidden="true"
      />
    </motion.div>
  );
}
