steps:
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: npm
    args: ['ci']
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: npm
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['rsync', '-r', '-d', './dist', 'gs://esa-cfs-versions/web/${BRANCH_NAME}']
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      [
        'setmeta',
        '-h',
        'cache-control:no-cache',
        'gs://esa-cfs-versions/web/${BRANCH_NAME}/*',
      ]
  - name: 'gcr.io/cloud-builders/curl'
    args: [
      '--data',
      '{"text": "New deployment to [${BRANCH_NAME}] is ready: \"${_HEAD_BRANCH}\" (${_PR_NUMBER})\n Visit: <https://storage.googleapis.com/esa-cfs-versions/web/${BRANCH_NAME}/index.html>\n Commit: <https://github.com/ubilabs/esa-climate-from-space/commit/${COMMIT_SHA}>"}',
      '${_SLACK_HOOK_URL}'
    ]

