steps:
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: npm
    args: ['ci']
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: npm
    args: ['run', 'eslint']
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: npm
    args: ['run', 'build']
  - name: 'gcr.io/esa-climate-from-space/electron-packager'
    entrypoint: electron-packager
    args: [
      '.',
      '--platform',
      'darwin',
      '--arch',
      'x64'
    ]
  - name: 'gcr.io/$PROJECT_ID/zip'
    args: ['-r', './esa-climate-from-space-darwin-x64.zip', './esa-climate-from-space-darwin-x64']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-J', './esa-climate-from-space-darwin-x64.zip', 'gs://esa-cfs-versions/${BRANCH_NAME}-electron']
 
