# build with "gcloud builds submit --config ./ci/cloudbuild-build-toolbox.yaml --timeout=2000 ./ci/docker"


steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/toolbox',
        '-f',
        './toolbox/Dockerfile',
        '.',
      ]
images:
  - 'gcr.io/$PROJECT_ID/toolbox'
