# build with "gcloud builds submit --config ./ci/cloudbuild-build-tile-mover.yaml ./ci/docker"

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/tile-mover',
        '-f',
        './tile-mover/Dockerfile',
        '.',
      ]
images:
  - 'gcr.io/$PROJECT_ID/tile-mover'
