steps:
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: npm
    args: ['ci']
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: npm
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['rm', '-r', 'gs://esa-cfs-versions/${BRANCH_NAME}']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', './dist', 'gs://esa-cfs-versions/${BRANCH_NAME}']
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      [
        'acl',
        'ch',
        '-r',
        '-u',
        'AllUsers:R',
        'gs://esa-cfs-versions/${BRANCH_NAME}/*',
      ]
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      [
        'setmeta',
        '-h',
        'cache-control:no-cache',
        'gs://esa-cfs-versions/${BRANCH_NAME}/*',
      ]
  - name: 'gcr.io/cloud-builders/curl'
    args: [
      '--data',
      '{"text": "New deployment from outer space is ready -> <https://storage.googleapis.com/esa-cfs-versions/${BRANCH_NAME}/index.html>"}',
      '_SLACK_HOOK_URL'
    ]
