steps:
  - name: 'node:22'
    entrypoint: npm
    args: ['ci']
  - name: 'node:22'
    entrypoint: npm
    args: ['run', 'eslint']
  - name: 'node:22'
    entrypoint: npm
    args: ['run', 'electron:compile']
  - name: 'node:22'
    entrypoint: npm
    args: ['run', 'build']
