# build with "gcloud builds submit --config ./ci/cloudbuild-build-electron-builder.yaml --timeout=2000 ./ci/docker"

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/electron-builder',
        '-f',
        './electron-builder/Dockerfile',
        '.',
      ]
images:
  - 'gcr.io/$PROJECT_ID/electron-builder'
