steps:
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: npm
    args: ['ci']
  - name: 'gcr.io/esa-climate-from-space/electron-builder'
    env:
      - 'ELECTRON_CACHE=/root/.cache/electron'
      - 'ELECTRON_BUILDER_CACHE=/root/.cache/electron-builder'
    entrypoint: 'npm'
    args: ['run', 'electron:build']
artifacts:
  objects:
    location: 'gs://esa-cfs-versions/electron/${BRANCH_NAME}'
    paths: ['./dist-electron/esa-climate*']
timeout: 1500s
