# manually run with "gcloud builds submit --config ./ci/cloudbuild-tiles.yaml --timeout=2000 --substitutions _LAYER_ID="fire.burned_area",_VARIABLE_ID="burned_area",_DATASET_ID="esacci.FIRE.mon.L4.BA.MODIS.Terra.MODIS_TERRA.v5-1.r1",_TIME_RANGE="2010-01-01.2011-01-01",_TILE_SIZE=256,_VERSION=0.0.1,_RESAMPLE_TIME=2m ."
steps:
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: 'mkdir'
    args:
      - "dataset.zarr"
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: 'gsutil'
    args:
      - "-m"
      - "cp"
      - "-r"
      - "gs://esa-cfs-cate-data/sst/dataset.zarr"
      - "./dataset.zarr/"
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: 'ls'
    args:
      - "-la"
      - "./dataset.zarr"
  - name: gcr.io/esa-climate-from-space/xcube:latest
    entrypoint: '/bin/bash'
    args:
      - "-c"
      - "conda run -n xcube chunk input_not_chunked.zarr -o output_rechunked.zarr --chunks "time=1,lat=270,lon=270""
  - name: gcr.io/esa-climate-from-space/xcube:latest
    entrypoint: '/bin/bash'
    args:
      - "-c"
      - "conda run -n xcube xcube tile --verbose --tile-size 256 --output ./tiles ./dataset.zarr/dataset.zarr"
  - name: gcr.io/cloud-builders/gsutil
    args:
      - "-m"
      - "cp"
      - "-r"
      - "./tiles"
      - "gs://esa-cfs-cate-data/sst/tiles/"
timeout: 4000s
options:
  diskSizeGb: 20
  machineType: 'N1_HIGHCPU_8'
