steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: 'download-netcdfs'
    entrypoint: '/bin/bash'
    args:
      - "-c"
      - "mkdir /data/netcdfs && gsutil -m cp -r gs://esa-cfs-cate-data/${_LAYER_ID}/*.nc /data/netcdfs/"

  - name: gcr.io/esa-climate-from-space/cate:latest
    id: 'cate-export-data-cube'
    entrypoint: '/bin/bash'
    args:
      - "-c"
      - "conda run -n cate-env python data/write-zarr.py --layer ${_LAYER_ID} --variable ${_VARIABLE_ID} --zoom-levels ${_ZOOM_LEVELS} --min ${_MIN} --max ${_MAX}"

  - name: geographica/gdal2:2.4.0
    id: 'gdal-generate-tiles'
    entrypoint: '/bin/bash'
    args:
       - "./data/gdal-reproject.sh"
       - "${_VARIABLE_ID}"
       - "${_ZOOM_LEVELS}"
       - "${_MIN_LON} ${_MIN_LAT} ${_MAX_LON} ${_MAX_LAT}"
       - "${_SOURCE_PROJECTION}"
       - "${_SOURCE_MIN_X} ${_SOURCE_MAX_Y} ${_SOURCE_MAX_X} ${_SOURCE_MIN_Y}"

  - name: gcr.io/esa-climate-from-space/tile-mover
    id: 'prepare-upload'
    entrypoint: '/bin/bash'
    args:
      - "./data/prepare-tile-upload.sh"
      - "${_VARIABLE_ID}"
      - "${_LAYER_ID}"

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: 'upload-to-storage'
    entrypoint: 'gsutil'
    args:
      - "-m"
      - "-q"
      - "cp"
      - "-r"
      - "/data/upload/${_LAYER_ID}/*"
      - "gs://esa-cfs-tiles/${_VERSION}/${_LAYER_ID}/"

options:
  substitution_option: 'ALLOW_LOOSE'
  diskSizeGb: 50
  volumes:
  - name: 'vol1'
    path: '/data'
